main : xyz.ch1ck.RandomWarp
name : RandomWarp
version : 0.1.0
api-version: '1.16'
author: chick_0
commands:
  setwarp:
    description: register warp point or delete warp point
    usage: /<command>
    permission: op
  warp:
    description: warp to random warp point
    usage: /<command>
